apiVersion: v1
kind: Service
metadata:
  name: resource-allocation-service-service # Change to your microservice name
spec:
  selector:
    app: resource-allocation-service  # This must match the app label in the Deployment
  ports:
    - protocol: TCP
      port: 5003  # Port for external access
      targetPort: 5000  # Port where the app is running in the container
  type: ClusterIP  # Use LoadBalancer if you want to expose it externally
---
