version: '3'
services:
  incident_reporting:
    build:
      context: ./services/incident_reporting
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./services/accountConfig.json:/app/accountConfig.json
    environment:
      - CONFIG_FILE=/app/accountConfig.json
    networks:
      - my_network

  severity_assessment:
    build:
      context: ./services/severity_assessment
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    volumes:
      - ./services/accountConfig.json:/app/accountConfig.json
    environment:
      - CONFIG_FILE=/app/accountConfig.json
    networks:
      - my_network

  resource_allocation:
    build:
      context: ./services/resource_allocation
      dockerfile: Dockerfile
    ports:
      - "5003:5000"
    volumes:
      - ./services/accountConfig.json:/app/accountConfig.json
    environment:
      - CONFIG_FILE=/app/accountConfig.json
    networks:
      - my_network

  communication:
    build:
      context: ./services/communication
      dockerfile: Dockerfile
    ports:
      - "5004:5000"
    volumes:
      - ./services/accountConfig.json:/app/accountConfig.json
    environment:
      - CONFIG_FILE=/app/accountConfig.json
    networks:
      - my_network

  situation_monitoring:
    build:
      context: ./services/situation_monitoring
      dockerfile: Dockerfile
    ports:
      - "5005:5000"
    volumes:
      - ./services/accountConfig.json:/app/accountConfig.json
    environment:
      - CONFIG_FILE=/app/accountConfig.json
    networks:
      - my_network

  incident_broadcast:
    build:
      context: ./services/incident_broadcast
      dockerfile: Dockerfile
    ports:
      - "5006:5000"
    volumes:
      - ./services/accountConfig.json:/app/accountConfig.json
    environment:
      - CONFIG_FILE=/app/accountConfig.json
    networks:
      - my_network


networks:
  my_network:
    driver: bridge