# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - resource

variables:
  # Docker Configuration
  serviceName: 'resource_allocation'
  dockerfilePath: '$(Build.SourcesDirectory)/services/$(serviceName)/Dockerfile'  # Path to the Dockerfile in the source directory
  imageRepository: 'resource'                              # Name of the image repository
  containerRegistry: 'drcscr.azurecr.io'    # URL of the Azure Container Registry
  dockerRegistryServiceConnection: 'DRCSCR'                # Service connection for Docker Registry
  subscriptionId: 'bc7270c6-c2c8-4ed5-82db-e53a4eac19f2'
  azureRMServiceConnection: 'azureRMService'  # Service connection for Azure
  
  # Build Metadata
  tag: '$(Build.BuildId)'                                  # Tag for the Docker image based on the build ID

pool:
  name: Default

steps:
  - task: Docker@2
    inputs:
      containerRegistry: '$(dockerRegistryServiceConnection)'
      repository: '$(containerRegistry)/$(imageRepository)'  # Correcting the repository path
      command: 'buildAndPush'
      Dockerfile: '$(dockerfilePath)'                        # Use variable for Dockerfile path
      tags: |
        $(tag)
        latest
    # Step 11: Verify that the image exists in Azure Container Registry
  - task: AzureCLI@2
    displayName: 'Verify Image in ACR'
    inputs:
      azureSubscription: $(azureRMServiceConnection)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az acr repository show-tags --name $(containerRegistry) --repository $(imageRepository) --output table --subscription $(subscriptionId)
