apiVersion: v1
kind: Service
metadata:
  name: incident-reporting-service-service # Change to your microservice name
spec:
  selector:
    app: incident-reporting-service  # This must match the app label in the Deployment
  ports:
    - protocol: TCP
      port: 5002  # Port for external access
      targetPort: 5000  # Port where the app is running in the container
  type: LoadBalancer  # Use LoadBalancer if you want to expose it externally
---