apiVersion: apps/v1
kind: Deployment
metadata:
  name: situation-monitoring-service  # Change to your microservice name
  labels:
    app: situation-monitoring-service  # Same name here
spec:
  replicas: 1  # Number of pod replicas
  selector:
    matchLabels:
      app: situation-monitoring-service  # Same name as above
  template:
    metadata:
      labels:
        app: situation-monitoring-service # Same name as above
    spec:
      containers:
      - name: situation-monitoring-service # Container name, usually the same as the service
        image: sabarinarayana/situation_monitoring:latest  # Replace with the Docker image for this microservice
        ports:
        - containerPort: 5000  # Port your microservice is running on
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 3
---
