apiVersion: apps/v1
kind: Deployment
metadata:
  name: situationMonitoringService  # Change to your microservice name
  labels:
    app: situationMonitoringService  # Same name here
spec:
  replicas: 1  # Number of pod replicas
  selector:
    matchLabels:
      app: situationMonitoringService  # Same name as above
  template:
    metadata:
      labels:
        app: situationMonitoringService # Same name as above
    spec:
      containers:
      - name: situationMonitoringService # Container name, usually the same as the service
        image: drcscr.azurecr.io/monitoring:latest # Replace with the Docker image for this microservice
        ports:
        - containerPort: 5000  # Port your microservice is running on
        env:
#        - name: ENV_VAR_NAME  # Optional environment variables
#          value: ENV_VAR_VALUE